---
- name: Add Nginx Repository
  apt_repository:
    repo: 'ppa:nginx/stable'
    state: present
  ignore_errors: yes

- name: Install Nginx
  apt:
    pkg: nginx
    state: installed
    update_cache: true
  notify:
    - Start Nginx

- name: Add Nginx Config
  copy:
    src: nginx_deb.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root

- name: Add Nginx Mime Types
  copy:
    src: mime.types
    dest: /etc/nginx/mime.types
    owner: root
    group: root

- name: Ensure Snippets Dir Exists
  file:
    path: /etc/nginx/snippets
    state: directory
    owner: root
    group: root

- name: Add Fastcgi-PHP
  copy:
    src: fastcgi-php.conf
    dest: /etc/nginx/snippets/fastcgi-php.conf
    owner: root
    group: root

- name: Disable Default Site
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Add Site Config
  template:
    src: lb.conf.j2
    dest: /etc/nginx/sites-available/lb.conf
    owner: root
    group: root
  notify:
    - Reload Nginx

- name: Enable Loadbalancer Config
  file:
    src: /etc/nginx/sites-available/lb.conf
    dest: /etc/nginx/sites-enabled/lb.conf
    state: link
  notify:
    - Reload Nginx